---
- name: Check ansible version
  import_playbook: ansible_version.yml

- hosts: bastion[0]
  gather_facts: False
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults}
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"]}

- name: Gather facts
  import_playbook: facts.yml

  #  roles:
  #  - { role: kubespray-defaults}
  #  - { role: reset, tags: reset }
