---
- name: look up docker cgroup driver
  shell: "docker info | grep 'Cgroup Driver' | awk -F': ' '{ print $2; }'"
  register: docker_cgroup_driver_result
  changed_when: false
  when: container_manager in ['crio', 'docker']

- name: set standalone_kubelet fact
  set_fact:
    standalone_kubelet: >-
      {%- if inventory_hostname in groups['kube-master'] and inventory_hostname not in groups['kube-node'] -%}true{%- else -%}false{%- endif -%}


# advertised host IP for kubelet. This affects network plugin config. Take caution
#kubelet_address: >-
#  {% if dualstack and ipfamily == "ipv6" %}
#  {{ip6 | default(fallback_ips[inventory_hostname])}}
#  {% else %}
#  {{ip | default(fallback_ips[inventory_hostname])}}
#  {% endif %}

# bind address for kubelet. Set to 0.0.0.0 to listen on all interfaces
#kubelet_bind_address: >-
#  {% if dualstack and ipfamily == "ipv6" %}
#  {{ip6 | default('0.0.0.0')}}
#  {% else %}
#  {{ip | default('0.0.0.0')}}
#  {% endif %}

- name: set kubelet_address
  set_fact:
    kubelet_address: "{{ ip6 }}"
    kubelet_bind_address: "{{ ip6 }}"
  when: dualstack is defined and ipfamily == 'ipv6' 

- name: set kubelet_cgroup_driver_detected fact for containerd
  set_fact:
    kubelet_cgroup_driver_detected: >-
      {%- if containerd_use_systemd_cgroup -%}systemd{%- else -%}cgroupfs{%- endif -%}
  when: container_manager == 'containerd'

- name: set kubelet_cgroup_driver_detected fact for other engines
  set_fact:
    kubelet_cgroup_driver_detected: "{{ docker_cgroup_driver_result.stdout }}"
  when: container_manager in ['crio', 'docker']

- name: os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
